#!/bin/bash -
curr=$(cd `dirname $(which $0)`; pwd)

cd $curr
make clean
# make default target is its first target
# in Makefile: fbs_parser
make
make fbs_lexer

if [ -f "automaton.dot" ]; then
    if [ -f "automaton.svg" ]; then
        rm automaton.svg
    fi
    #dot -T svg automaton.dot > automaton.svg
fi
